callback/urls.py
from django.urls import path
from callback.views import callback_form

urlpatterns = [
    path('request/', callback_form, name='request'),
]

som/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView
from django.shortcuts import render
from index.views import index
from index.sitemap import IndexSitemap
from bridges.sitemap import BridgeSitemap
from bridges.views import bridges
from contacts.sitemap import ContactsSitemap
from contacts.views import contacts
from porch.sitemap import PorchSitemap
from railings.sitemap import RailingSitemap
from staircases.sitemap import StaircaseSitemap
from terraces.sitemap import TerraceSitemap
from terraces.views import terraces

sitemaps = {
    'index': IndexSitemap,
    'staircase': StaircaseSitemap,
    'railing': RailingSitemap,
    # 'steps': StepsSitemap,
    'terrace': TerraceSitemap,
    'porch': PorchSitemap,
    'bridge': BridgeSitemap,
    'contacts': ContactsSitemap,
}


urlpatterns = [
    path('admin/logout/', auth_views.LogoutView.as_view(next_page='/admin/login'), name='logout'),
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('decorative-bridge/', bridges, name='decorative-bridge'),
    path('terrace/', terraces, name='terrace'),
    path('callback/', include(('callback.urls', 'callback'), namespace='callback')),
    path('staircases/', include(('staircases.urls', 'staircases'), namespace='staircases')),
    path('railings/', include(('railings.urls', 'railings'), namespace='railings')),
    path('porch/', include(('porch.urls', 'porch'), namespace='porch')),
    # path('steps/', include(('steps.urls', 'steps'), namespace='steps')),
    path('privacy-policy/', TemplateView.as_view(
        template_name="privacy-policy/index.html"), name="privacy-policy"),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]

admin.site.site_header = admin.site.site_title = 'ПМ «Студия Металла»'

def handler400(request, exception, template_name='errors/400.html'):
    response = render(request, template_name)
    response.status_code = 400
    return response


def handler403(request, exception, template_name='errors/403.html'):
    response = render(request, template_name)
    response.status_code = 403
    return response


def handler404(request, exception, template_name='errors/404.html'):
    response = render(request, template_name)
    response.status_code = 404
    return response

# def handler404(request, exception):
#     return render(request, 'errors/404.html', status=404)


def handler500(request, template_name='errors/500.html'):
    response = render(request, template_name)
    response.status_code = 500
    return response


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns

    urlpatterns += [
        path('400/', TemplateView.as_view(template_name="errors/400.html")),
        path('403/', TemplateView.as_view(template_name="errors/403.html")),
        path('404/', TemplateView.as_view(template_name="errors/404.html")),
        path('500/', TemplateView.as_view(template_name="errors/500.html")),
    ]

    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(r'/favicon.ico', document_root='static/favicon.ico')
    # urlpatterns += static(r'/site.webmanifest', document_root='static/site.webmanifest')

callback/forms.py
from django import forms


class CallbackForm(forms.Form):
    name = forms.CharField(
        max_length=50, label='Ваше имя', required=True,
        widget=forms.TextInput(attrs={'class': 'form-control', }),)
    phone = forms.CharField(
        max_length=50, label='Ваш номер телефона', required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'data-phone-pattern': '',
        }),)
    recaptcha = forms.CharField(widget=forms.HiddenInput(
        attrs={'class': 'g-recaptcha-response', }
    ))

callback/views.py
import json
import os
import requests
from datetime import datetime, timezone
from django.conf import settings
from django.http import HttpResponse
from callback.forms import CallbackForm
from common.loggers import logger
from django.template.loader import render_to_string
from django.core.mail import send_mail


def callback_form(request):
    if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest' and request.method == 'POST':
        form = CallbackForm(request.POST)
        if form.is_valid():

            if 'RECAPTCHA_DISABLE' in os.environ.keys(): # For tests
                res = json.loads(request.POST.get('recaptcha'))
            else:
                recaptcha_response = request.POST.get('recaptcha')
                data = {
                    'secret': settings.RECAPTCHA_PRIVATE_KEY,
                    'response': recaptcha_response
                }
                req = requests.post(
                    'https://www.google.com/recaptcha/api/siteverify', 
                    data=data
                )

                res = req.json()

            if res['success'] == True and res['score'] >= 0.5:
                subject = 'Обратный звонок'
                name = form.cleaned_data.get('name')
                phone = form.cleaned_data.get('phone')

                context = {
                    'subject': subject,
                    'name': name,
                    'phone': phone,
                    'date': datetime.now(timezone.utc)
                }

                html_body = render_to_string(
                    'callback/email/callback.html', 
                    context
                )

                text_body = render_to_string(
                    'callback/email/callback.txt', 
                    context
                )

                try:
                    send_mail(
                        subject,
                        message=text_body,
                        html_message=html_body,
                        recipient_list=settings.LIST_OF_EMAIL_RECIPIENTS,
                        from_email=settings.EMAIL_HOST_USER,
                        fail_silently=False,
                    )

                    # msg = 'Ваш запрос был успешно отправлен. Спасибо!'
                    # logger.info(msg)
                    # return HttpResponse(msg, status=200)
                    msg = {
                        'status': 'ok', 
                        'message': 'Ваш запрос был успешно отправлен. Спасибо!'
                    }
                    logger.info(msg)
                    return HttpResponse(json.dumps(msg))

                except Exception as e:
                    logger.error(e)

                    msg = {
                        'status': 'error',
                        'message': 'Произошла ошибка. Пожалуйста попробуйте позже.'
                    }
                    return HttpResponse(json.dumps(msg))
            else:
                # msg = 'Ошибка reCAPTCHA. Пожалуйста попробуйте позже.'
                # logger.info(msg)
                # return HttpResponse(msg, status=400)
                msg = {
                    'status': 'error',
                    'message': 'Ошибка reCAPTCHA. Пожалуйста попробуйте позже.'
                }
                logger.info(msg)
                return HttpResponse(json.dumps(msg))
        else:
            # msg = 'Произошла ошибка. Пожалуйста попробуйте позже.'
            # logger.info(msg)
            # return HttpResponse(msg, status=400)
            msg = {
                'status': 'error',
                'message': 'Произошла ошибка. Пожалуйста попробуйте позже.'
            }
            logger.info(msg)
            return HttpResponse(json.dumps(msg))
    else:
        return HttpResponse(status=405)  

templates/callback/_form.html
{% load recaptcha3 sekizai_tags %}

{% addtoblock 'recaptcha' %}
{% comment %} {% recaptcha_init %} {% endcomment %}
<script src="https://www.google.com/recaptcha/api.js?render={{ recaptcha_key }}"></script>

  <script>
    //global grecaptcha
    grecaptcha.ready(function() {
      grecaptcha.execute('{{ recaptcha_key }}').then(function(token) {
        {% comment %} document.getElementById('g-recaptcha-response').value = token; {% endcomment %}
        document.getElementById('id_recaptcha').value = token;
      });
    });
  </script>
{% comment %} 
  <script>
    //global grecaptcha
    grecaptcha.ready(function() {
      grecaptcha.execute('{{ recaptcha_key }}', {action: "{% url "callback:request" %}"}).then(function(token) {
        document.getElementById('id_recaptcha').value = token;
      });
    });
  </script> {% endcomment %}

{% endaddtoblock %}

{% block content %}
<section id="callback">
  <div class="container mb-5">
    <div class="section-title">
      <span>Обратный звонок</span>
    </div>
    <div class="row d-flex justify-content-center">
    {% comment %} <div class="container">
      <div class="row"> {% endcomment %}
        <div class="col-6">
      {% if callback_form.errors %}
            <div class="alert alert-danger">
                Пожалуйста исправьте ошибки.
                <a class="close" data-dismiss="alert">×</a>
            </div>
        {% endif %}
        <form action="{% url "callback:request" %}" method="post" role="form" class="callback-form">{% csrf_token %}
        {% comment %} <form method="post" role="form" class="callback-form">{% csrf_token %} {% endcomment %}
          <div class="overlay-wrapper p-3">
            <div class="overlay">
                <div class="loading d-none spinner-border text-primary" role="status">
                  <span class="visually-hidden">Loading...</span>
                </div>
                <div class="error-message d-none" role="alert">
                  <i class="fas fa-exclamation-triangle fa-lg"></i>
                </div>
                {% comment %} <div class="alert alert-success" role="alert"> {% endcomment %}
                <div class="sent-message d-none" role="alert">
                  <i class="far fa-check-circle fa-lg me-3"></i>
                </div>
            </div>
              <div class="row g-3">
                <div class="col-12">
                  <div class="form-floating">
                    {% comment %} <input
                      type="text"
                      class="form-control bg-light border-0"
                      id="name"
                      placeholder="Your Name"
                    /> {% endcomment %}
                    {{ callback_form.name }}
                    <label for="{{ callback_form.name.id_for_label }}">{{ callback_form.name.label }}</label>
                  </div>
                </div>
                <div class="col-12">
                  <div class="form-floating">
                    {% comment %} <input
                      type="email"
                      class="form-control bg-light border-0"
                      id="email"
                      placeholder="Your Email"
                    /> {% endcomment %}
                    {{ callback_form.phone }}
                    <label for="{{ callback_form.phone.id_for_label }}">{{ callback_form.phone.label }}</label>
                  </div>
                </div>
                {% comment %} {{ callback_form.captcha }} {% endcomment %}
                {{ callback_form.recaptcha }}
                <div class="col-12">
                    <small>Даю своё согласие на обработку персональных данных. <a href="{% url "privacy-policy" %}">Правила&nbsp;обработки</a>.</small>
                </div>
               
                <div class="col-12 mt-4">
                  <button class="btn btn-primary px-4" type="submit">
                    Отправить
                  </button>
                </div>
                {% comment %} <div class="my-3">
                  <div class="loading">Loading</div>
                  <div class="error-message"></div>
                  <div class="sent-message">Your message has been sent. Thank you!</div>
                </div> {% endcomment %}
              </div>
            </div>
            </form>
          </div>

        {% comment %} <form method="POST">{% csrf_token %}
            <div class="form-group {% if form.name.errors %}has-error{% endif %}">
                <label for="{{ form.name.id_for_label }}" class="control-label">{{ form.name.label }}</label>
                        <div class="input-group mb-3">
                          <div class="input-group-prepend">
                              <span class="input-group-text">
                    <i class="fa fa-envelope" aria-hidden="true"></i></span>
                </div>
                    {{ form.name }}
                </div>
                {% if form.name.errors %}
                    <span class="text-danger">{{ form.name.errors.as_text }}</span>
                {% endif %}
            </div>
            <div class="form-group {% if form.phone.errors %}has-error{% endif %}">
                <label for="{{ form.phone.id_for_label }}" class="control-label">{{ form.phone.label }}</label>
                        <div class="input-group mb-3">
                          <div class="input-group-prepend">
                              <span class="input-group-text">
                    <i class="fa fa-crosshairs" aria-hidden="true"></i></span>
                </div>
                    {{ form.phone }}
                </div>
                {% if form.phone.errors %}
                    <span class="text-danger">{{ form.phone.errors.as_text }}</span>
                {% endif %}
            </div>
                <div class="form-group">
                <div class="g-recaptcha" data-sitekey="6LcfcnEUAAAAANbuWiTnecdyHkLi7La0Z0W3Cerf"></div>
                {% if form.captcha.errors %}
                    <span class="text-danger">{{ form.captcha.errors.as_text }}</span>
                {% endif %}
            </div>
            <button class="btn btn-primary" type="submit">Отправить</button>
        </form> {% endcomment %}
{% comment %} </div>
</div> {% endcomment %}
</div>
</section>
{% endblock %}

templates/callback/form.html
<form action="{% url "callback:request" %}" data-recaptcha-site-key="{{ recaptcha_key }}" method="post" class="callback-form">{% csrf_token %}
  <div class="overlay-wrapper p-3">
    <div class="overlay">
      <div class="loading d-none spinner-border text-primary" role="status">
        <span class="visually-hidden">Loading...</span>
      </div>
      <div class="error-message d-none" role="alert">
        <i class="fas fa-exclamation-triangle fa-lg"></i>
      </div>
      <div class="sent-message d-none" role="alert">
        <i class="far fa-check-circle fa-lg me-3"></i>
      </div>
    </div>
    <div class="row g-3">
      <div class="col-12">
        <div class="form-floating">
          {{ callback_form.name }}
          <label for="{{ callback_form.name.id_for_label }}">{{ callback_form.name.label }}</label>
        </div>
      </div>
      <div class="col-12">
        <div class="form-floating">
          {{ callback_form.phone }}
          <label for="{{ callback_form.phone.id_for_label }}">{{ callback_form.phone.label }}</label>
        </div>
      </div>
      {{ callback_form.recaptcha }}
      <div class="col-12">
        <small>Даю своё согласие на обработку персональных данных. <a href="{% url "privacy-policy" %}" rel="nofollow">Правила&nbsp;обработки</a>.</small>
      </div>
      <div class="col-12 mt-4">
        <button class="btn btn-primary px-4" type="submit">Отправить</button>
      </div>
    </div>
  </div>
</form>

templates/callback/index.html
{% comment %} {% addtoblock 'recaptcha' %}
<script src="https://www.google.com/recaptcha/api.js?render={{ recaptcha_key }}"></script>
<script>
  grecaptcha.ready(function() {
    grecaptcha.execute('{{ recaptcha_key }}').then(function(token) {
      document.getElementById('id_recaptcha').value = token;
    });
  });
</script>
{% endaddtoblock %} {% endcomment %}

{% block content %}
<!--noindex-->
<div id="callback" class="section">
  <div class="container mb-5">
    <div class="section-title">
      <span>Консультация специалиста</span>
      <p class="fst-italic">Наш менеджер ответит Вам в течении 15 минут.</p>
    </div>
    <div class="row d-flex justify-content-center">
      <div class="col-md-8 col-lg-6">
        {% include 'callback/form.html' %}
      </div>
    </div>
  </div>
</div>
<!--/noindex-->
{% endblock %}

templates/callback/modal.html
<div class="modal fade" id="callback_modal" tabindex="-1" aria-labelledby="callback_modal_label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <span class="modal-title fs-5" id="callback_modal_label">Заказать обратный звонок</span>
        {% comment %} <button type="button" data-bs-dismiss="modal" aria-label="Close"><i class="fas fa-times fa-lg"></i></button> {% endcomment %}
        <a href="#" data-bs-dismiss="modal" aria-label="Close"><i class="fas fa-times fa-lg"></i></a>
      </div>
      <div class="modal-body">
      {% include 'callback/form.html' %}
      </div>
    </div>
  </div>
</div>