porch/urls.py
from django.urls import path
from porch.views import porch

urlpatterns = [
    path('<slug:slug>/', porch, name='detail'),
]

som/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView
from django.shortcuts import render
from index.views import index
from index.sitemap import IndexSitemap
from bridges.sitemap import BridgeSitemap
from bridges.views import bridges
from contacts.sitemap import ContactsSitemap
from contacts.views import contacts
from porch.sitemap import PorchSitemap
from railings.sitemap import RailingSitemap
from staircases.sitemap import StaircaseSitemap
from terraces.sitemap import TerraceSitemap
from terraces.views import terraces

sitemaps = {
    'index': IndexSitemap,
    'staircase': StaircaseSitemap,
    'railing': RailingSitemap,
    # 'steps': StepsSitemap,
    'terrace': TerraceSitemap,
    'porch': PorchSitemap,
    'bridge': BridgeSitemap,
    'contacts': ContactsSitemap,
}


urlpatterns = [
    path('admin/logout/', auth_views.LogoutView.as_view(next_page='/admin/login'), name='logout'),
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('decorative-bridge/', bridges, name='decorative-bridge'),
    path('terrace/', terraces, name='terrace'),
    path('callback/', include(('callback.urls', 'callback'), namespace='callback')),
    path('staircases/', include(('staircases.urls', 'staircases'), namespace='staircases')),
    path('railings/', include(('railings.urls', 'railings'), namespace='railings')),
    path('porch/', include(('porch.urls', 'porch'), namespace='porch')),
    # path('steps/', include(('steps.urls', 'steps'), namespace='steps')),
    path('privacy-policy/', TemplateView.as_view(
        template_name="privacy-policy/index.html"), name="privacy-policy"),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]

admin.site.site_header = admin.site.site_title = 'ПМ «Студия Металла»'

def handler400(request, exception, template_name='errors/400.html'):
    response = render(request, template_name)
    response.status_code = 400
    return response


def handler403(request, exception, template_name='errors/403.html'):
    response = render(request, template_name)
    response.status_code = 403
    return response


def handler404(request, exception, template_name='errors/404.html'):
    response = render(request, template_name)
    response.status_code = 404
    return response

# def handler404(request, exception):
#     return render(request, 'errors/404.html', status=404)


def handler500(request, template_name='errors/500.html'):
    response = render(request, template_name)
    response.status_code = 500
    return response


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns

    urlpatterns += [
        path('400/', TemplateView.as_view(template_name="errors/400.html")),
        path('403/', TemplateView.as_view(template_name="errors/403.html")),
        path('404/', TemplateView.as_view(template_name="errors/404.html")),
        path('500/', TemplateView.as_view(template_name="errors/500.html")),
    ]

    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(r'/favicon.ico', document_root='static/favicon.ico')
    # urlpatterns += static(r'/site.webmanifest', document_root='static/site.webmanifest')

menu/models.py
from django.db import models
from treebeard.mp_tree import MP_Node


class Menu(MP_Node):
    name = models.CharField('название', max_length=30)
    url = models.CharField('url-адрес страницы', max_length=100, blank=True)
    is_visible = models.BooleanField('показывать?', default=1)

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = 'меню'
        verbose_name_plural = 'меню'

menu/views.py
from django.shortcuts import render

# Create your views here.

templates/_line-dark-background.html
<div class="line">
<div class="line-content line-content--dark_background">

<svg class="line-icon" xmlns="http://www.w3.org/2000/svg" xml:space="preserve" width="40px" height="40px" version="1.1" style="shape-rendering:geometricPrecision; text-rendering:geometricPrecision; image-rendering:optimizeQuality; fill-rule:evenodd; clip-rule:evenodd"
viewBox="0 0 40 40">
 <g id="monogram_light">
  <g id="_1326610320">
   <path class="fil0_light str0_light" d="M12.47 19.74l7.28 -7.28 -3.28 -3.29c-0.87,-0.86 -1.41,-2.06 -1.41,-3.38 0,-2.64 2.3,-4.79 4.94,-4.79 2.64,0 5,2.22 5,4.86 0,1.32 -0.63,2.52 -1.5,3.38l-3.24 3.22 7.28 7.29 3.29 -3.28c0.86,-0.87 2.06,-1.41 3.38,-1.41 2.64,0 4.79,2.3 4.79,4.94 0,2.64 -2.22,5 -4.86,5 -1.32,0 -2.52,-0.63 -3.38,-1.5l-3.22 -3.23 -7.29 7.28 3.28 3.28c0.87,0.86 1.41,2.06 1.41,3.38 0,2.64 -2.3,4.79 -4.94,4.79 -2.64,0 -5,-2.22 -5,-4.86 0,-1.32 0.63,-2.52 1.5,-3.38l3.24 -3.22 -7.28 -7.29 -3.29 3.28c-0.86,0.87 -2.06,1.41 -3.38,1.41 -2.64,0 -4.79,-2.3 -4.79,-4.94 0,-2.64 2.22,-5 4.86,-5 1.32,0 2.52,0.63 3.38,1.5l3.23 3.24zm0.8 0.26l6.73 -6.73 6.73 6.73 -6.73 6.74 -6.73 -6.74zm-4.52 -2.85c-0.78,-0.74 -1.73,-1.39 -2.94,-1.37 -2.34,0.04 -4.04,1.97 -4.03,4.22 0,2.23 1.67,4.1 4.03,4.15 1.18,0.02 2.14,-0.44 2.89,-1.17l3.07 -2.98 -0.01 0 0 0 -3.01 -2.85zm14.1 -8.4c0.74,-0.78 1.39,-1.73 1.37,-2.94 -0.04,-2.34 -1.97,-4.04 -4.22,-4.03 -2.23,0 -4.1,1.66 -4.15,4.03 -0.02,1.18 0.44,2.14 1.17,2.88l2.98 3.07 0 0 0 0 2.85 -3.01zm8.4 14.1c0.78,0.74 1.73,1.39 2.94,1.37 2.34,-0.04 4.04,-1.97 4.03,-4.22 0,-2.24 -1.67,-4.1 -4.03,-4.15 -1.18,-0.02 -2.14,0.44 -2.89,1.16l-3.07 2.99 0.01 0 0 0 3.01 2.85zm-14.1 8.4c-0.74,0.78 -1.39,1.73 -1.37,2.94 0.04,2.34 1.97,4.04 4.22,4.03 2.23,0 4.1,-1.67 4.15,-4.03 0.02,-1.18 -0.44,-2.14 -1.17,-2.89l-2.98 -3.07 0 0.01 0 0 -2.85 3.01z"/>
   <path class="fil0_light str0_light" d="M10.88 29.69l-0.48 0.62c0.33,0.79 0.25,1.63 -0.6,2.25 -0.19,0.24 -0.38,0.54 -0.43,1.03 -1.04,0.64 -0.72,-1.2 -0.22,-1.7 -0.1,-0.09 -0.19,-0.18 -0.28,-0.27 -0.57,0.7 -1.06,1.41 -1.47,2.13 -0.3,-0.08 -0.64,0.01 -0.64,0.01l-0.77 0.52c-0.29,-0.02 -0.24,0.03 -0.25,-0.26l0.51 -0.78c0,0 0.09,-0.34 0,-0.63 0.73,-0.41 1.44,-0.91 2.14,-1.47 -0.1,-0.1 -0.18,-0.19 -0.27,-0.28 -0.5,0.5 -2.34,0.82 -1.71,-0.22 0.49,-0.05 0.8,-0.24 1.04,-0.43 0.61,-0.86 1.46,-0.93 2.24,-0.61l0.54 -0.4 18.96 -18.92 0.41 -0.58c-0.33,-0.79 -0.25,-1.63 0.61,-2.25 0.19,-0.23 0.37,-0.54 0.43,-1.03 1.04,-0.64 0.72,1.2 0.22,1.71 0.09,0.08 0.18,0.17 0.28,0.26 0.56,-0.7 1.06,-1.41 1.46,-2.13 0.3,0.08 0.64,0 0.64,0l0.77 -0.52c0.3,0.01 0.25,-0.04 0.26,0.25l-0.52 0.78c0,0 -0.08,0.34 0,0.64 -0.72,0.4 -1.43,0.9 -2.13,1.46 0.09,0.1 0.18,0.18 0.26,0.28 0.51,-0.5 2.35,-0.82 1.71,0.22 -0.49,0.06 -0.8,0.24 -1.03,0.43 -0.62,0.86 -1.46,0.94 -2.25,0.61l-0.54 0.39 -18.89 18.89z"/>
   <path class="fil0_light str0_light" d="M29.69 29.13l0.62 0.48c0.79,-0.33 1.63,-0.26 2.25,0.6 0.24,0.19 0.54,0.38 1.03,0.43 0.64,1.04 -1.2,0.72 -1.7,0.22 -0.09,0.1 -0.18,0.19 -0.27,0.28 0.7,0.57 1.41,1.06 2.13,1.47 -0.08,0.3 0.01,0.64 0.01,0.64l0.52 0.77c-0.02,0.29 0.03,0.24 -0.26,0.25l-0.78 -0.51c0,0 -0.34,-0.09 -0.63,0 -0.41,-0.73 -0.91,-1.44 -1.47,-2.14 -0.1,0.1 -0.19,0.18 -0.28,0.27 0.5,0.5 0.82,2.34 -0.22,1.7 -0.06,-0.48 -0.24,-0.79 -0.43,-1.03 -0.86,-0.62 -0.93,-1.46 -0.61,-2.24l-0.4 -0.54 -18.92 -18.96 -0.58 -0.41c-0.79,0.33 -1.63,0.25 -2.25,-0.61 -0.23,-0.19 -0.55,-0.37 -1.03,-0.43 -0.64,-1.04 1.2,-0.72 1.71,-0.22 0.08,-0.1 0.17,-0.18 0.26,-0.28 -0.7,-0.56 -1.41,-1.06 -2.13,-1.46 0.08,-0.3 0,-0.64 0,-0.64l-0.52 -0.77c0.01,-0.3 -0.04,-0.25 0.25,-0.26l0.78 0.52c0,0 0.34,0.08 0.64,0 0.4,0.72 0.9,1.43 1.46,2.13 0.1,-0.09 0.18,-0.18 0.28,-0.26 -0.5,-0.51 -0.82,-2.35 0.22,-1.71 0.06,0.49 0.24,0.8 0.43,1.03 0.86,0.62 0.94,1.46 0.61,2.25l0.39 0.54 18.89 18.89z"/>
   <path class="fil0_light str0_light" d="M9.11 33.48c0.13,-0.81 0.65,-1.09 1.25,-1.8 0.1,-0.21 0.05,-0.35 -0.61,-0.04 -0.66,0.62 -0.99,1.34 -0.64,1.84z"/>
   <path class="fil0_light str0_light" d="M33.47 30.9c-0.8,-0.13 -1.08,-0.65 -1.79,-1.25 -0.21,-0.1 -0.35,-0.05 -0.05,0.61 0.63,0.65 1.34,0.99 1.84,0.64z"/>
   <path class="fil0_light str0_light" d="M30.9 6.54c-0.13,0.8 -0.65,1.08 -1.25,1.79 -0.1,0.21 -0.05,0.35 0.6,0.05 0.66,-0.63 1,-1.34 0.65,-1.84z"/>
   <path class="fil0_light str0_light" d="M6.53 9.11c0.81,0.13 1.09,0.65 1.8,1.25 0.21,0.1 0.35,0.05 0.04,-0.61 -0.62,-0.65 -1.34,-0.99 -1.84,-0.64z"/>
   <path class="fil0_light str0_light" d="M6.54 30.89c0.8,-0.13 1.09,-0.65 1.79,-1.25 0.21,-0.1 0.35,-0.05 0.05,0.61 -0.63,0.65 -1.34,0.99 -1.84,0.64z"/>
   <path class="fil0_light str0_light" d="M30.89 33.47c-0.13,-0.8 -0.66,-1.09 -1.26,-1.79 -0.1,-0.21 -0.05,-0.35 0.61,-0.05 0.66,0.63 0.99,1.34 0.65,1.84z"/>
   <path class="fil0_light str0_light" d="M33.47 9.12c-0.81,0.13 -1.09,0.66 -1.8,1.26 -0.21,0.1 -0.35,0.04 -0.04,-0.61 0.62,-0.66 1.34,-0.99 1.84,-0.65z"/>
   <path class="fil0_light str0_light" d="M9.12 6.54c0.13,0.81 0.65,1.09 1.25,1.8 0.1,0.21 0.05,0.35 -0.61,0.04 -0.65,-0.62 -0.99,-1.34 -0.64,-1.84z"/>
   <circle class="fil0_light str0_light" transform="matrix(-0.00245553 -0.00245553 0.00245553 -0.00245553 9.41191 30.5962)" r="162.3"/>
   <circle class="fil0_light str0_light" transform="matrix(-0.00245553 0.00245553 -0.00245553 -0.00245553 30.5928 30.5978)" r="162.3"/>
   <circle class="fil0_light str0_light" transform="matrix(0.00245553 0.00245553 -0.00245553 0.00245553 30.5944 9.41694)" r="162.3"/>
   <circle class="fil0_light str0_light" transform="matrix(0.00245553 -0.00245553 0.00245553 0.00245553 9.41351 9.41534)" r="162.3"/>
   <circle class="fil0_light str0_light" transform="matrix(-0.00127088 -0.00127088 0.00127088 -0.00127088 9.41191 30.5944)" r="162.3"/>
   <circle class="fil0_light str0_light" transform="matrix(-0.00127088 0.00127088 -0.00127088 -0.00127088 30.591 30.5978)" r="162.3"/>
   <circle class="fil0_light str0_light" transform="matrix(0.00127088 0.00127088 -0.00127088 0.00127088 30.5944 9.41878)" r="162.3"/>
   <circle class="fil0_light str0_light" transform="matrix(0.00127088 -0.00127088 0.00127088 0.00127088 9.41534 9.41534)" r="162.3"/>
   <path class="fil0_light str0_light" d="M6.79 33.44l1.97 -1.98c0.14,-0.13 -0.07,-0.35 -0.21,-0.21l-1.97 1.98c-0.83,0.82 -0.61,1.03 0.21,0.21z"/>
   <path class="fil0_light str0_light" d="M33.44 33.22l-1.98 -1.97c-0.14,-0.14 -0.35,0.07 -0.21,0.21l1.98 1.97c0.82,0.83 1.03,0.61 0.21,-0.21z"/>
   <path class="fil0_light str0_light" d="M33.22 6.57l-1.98 1.98c-0.13,0.13 0.08,0.35 0.21,0.21l1.98 -1.98c0.83,-0.82 0.61,-1.03 -0.21,-0.21z"/>
   <path class="fil0_light str0_light" d="M6.57 6.79l1.98 1.98c0.13,0.13 0.35,-0.08 0.21,-0.22l-1.98 -1.97c-0.82,-0.83 -1.03,-0.61 -0.21,0.21z"/>
   <ellipse class="fil0_light str0_light" cx="16.47" cy="16.53" rx="0.77" ry="0.82"/>
   <ellipse class="fil0_light str0_light" cx="20" cy="12.44" rx="0.77" ry="0.82"/>
   <ellipse class="fil0_light str0_light" cx="23.72" cy="16.42" rx="0.77" ry="0.82"/>
   <ellipse class="fil0_light str0_light" cx="27.5" cy="20.1" rx="0.77" ry="0.82"/>
   <ellipse class="fil0_light str0_light" cx="20.05" cy="20.2" rx="0.77" ry="0.82"/>
   <ellipse class="fil0_light str0_light" cx="12.69" cy="20.1" rx="0.77" ry="0.82"/>
   <ellipse class="fil0_light str0_light" cx="16.37" cy="23.68" rx="0.77" ry="0.82"/>
   <ellipse class="fil0_light str0_light" cx="20.05" cy="27.56" rx="0.77" ry="0.82"/>
   <ellipse class="fil0_light str0_light" cx="23.83" cy="23.78" rx="0.77" ry="0.82"/>
  </g>
 </g>
</svg>

</div>
</div>

templates/_navbar.html

<nav class="navbar navbar-expand-md navbar-dark">
  <div class="container-fluid">
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarCollapse"
      aria-controls="navbarCollapse"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 menu-line">
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            data-bs-toggle="dropdown"
            aria-expanded="false"
            >Лестницы</a
          >
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li>
              <a class="dropdown-item" href="#">Something else here</a>
            </li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            data-bs-toggle="dropdown"
            aria-expanded="false"
            >Перила</a
          >
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li>
              <a class="dropdown-item" href="#">Something else here</a>
            </li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            data-bs-toggle="dropdown"
            aria-expanded="false"
            >Ступени</a
          >
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li>
              <a class="dropdown-item" href="#">Something else here</a>
            </li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            data-bs-toggle="dropdown"
            aria-expanded="false"
            >Крыльцо</a
          >
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li>
              <a class="dropdown-item" href="#">Something else here</a>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Контакты</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/description.html
{% load markdownify cache app_label %}
{% cache cache_timeout descrition object|app_label object.id %}
{% include "line-blue-background.html" %}
<section class="description">
  <div class="container">
    {% if object.description_title %}
    <div class="section-title">
      <h2>{{object.description_title}}</h2>
    </div>
    {% endif %}
    {{object.description_text|markdownify}}
  </div>
</section>
{% endcache %}

templates/footer.html
<footer class="footer mt-auto">
  <div class="container pt-5 px-4 px-sm-0">
    <div class="row mb-4">
      <div class="col-md-8">
        <div class="mb-2">
          <i class="fa fa-phone-alt"></i>
          <a href="tel:+79633056757">+7 (963) 305-67-57</a>
          {% comment %} <a href="tel:+79219451942">+7 (921) 945-19-42</a> {% endcomment %}
        </div>
        <div class="mb-2"><i class="fa fa-envelope"></i>
          <a href="mailto:info@studio-of-metal.ru">info@studio-of-metal.ru</a>
        </div>
        <div class="footer-address">
          <i class="fa fa-map-marker-alt pt-1"></i>
          <div>г.&nbsp;Санкт-Петербург,&nbsp;проспект&nbsp;9&nbsp;января,&nbsp;д.13,&nbsp;к.1</div>
        </div>
      </div>
      <div class="col-md-4 mt-3">
        <div class="d-flex justify-content-center justify-content-md-end">
          <a class="btn-social btn-whatsapp" href="https://api.whatsapp.com/send?phone=79633056757" target="_blank" rel="noopener nofollow" aria-label="Whatsapp">
            <i class="fab fa-whatsapp"></i>
          </a>
          <a class="btn-social btn-telegram" href="https://t.me/+79633056757" target="_blank" rel="noopener nofollow" aria-label="Телеграм">
            <i class="fab fa-telegram-plane"></i>
          </a>
          <a class="btn-social btn-vk" href="https://vk.com/public202109189" target="_blank" rel="noopener nofollow" aria-label="Вконтакте">
            <i class="fab fa-vk"></i>
          </a>
          {% comment %} <a class="btn-social btn-instagram" href="https://www.instagram.com/lestnica_v_dom_spb/" target="_blank" rel="noopener" aria-label="Инстаграм">
            <i class="fab fa-instagram"></i>
          </a> {% endcomment %}
          <a class="btn-social btn-youtube" href="https://www.youtube.com/channel/UCMrVSYMuyIifKcLg6MuMXkA" target="_blank" rel="noopener nofollow" aria-label="Youtube">
            <i class="fab fa-youtube"></i>
          </a>
        </div>
      </div>
    </div>

    <div class="row copyright">
      <div class="col-md-6">
        <div class="row">
          <div class="col-md-12">
            <i class="far fa-copyright"></i><a href="/">ПМ "Студия Металла"</a>, <span><script>document.write(new Date().getFullYear());</script></span>
          </div>
          <div class="col-md-12">
            <i class="fas fa-user-shield"></i><a href="/privacy-policy/" rel="noindex, nofollow">Политика конфиденциальности</a>
          </div>
        </div>
      </div>
      <div class="col-md-6 mt-2 mt-md-0">
        <p style="text-align: justify; line-height: 1.5; font-size: 12px;">Представленные цены носят ознакомительный характер и не являются публичной офертой, определяемой положениями ст. 437 Гражданского кодекса РФ.</p>
      </div>
    </div>
  </div>
</footer>

templates/head.html
{% load static %}
<title>{{ object.head_title }}</title>
<meta name="description" content="{{ object.meta_description }}">
<meta property="og:title" content="{{ object.head_title }}">
<meta property="og:description" content="{{ object.meta_description }}">
<meta property="og:type" content="website">
<meta property="og:image" content="{{host}}{% static 'images/logo-black-300x43.png' %}">

templates/navbar.html
{% load static cache menu %}
<nav class="navbar navbar-expand-md navbar-dark py-md-0" itemscope itemtype="http://schema.org/SiteNavigationElement">
  <a href="/" class="navbar-brand d-md-none d-xs-block" itemprop="url">
    <img src="{% static 'images/logo.svg' %}" alt="ПМ Студия Металла" width="260">
  </a>
  <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-label="Меню">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <div class="navbar-nav">
      {% cache cache_timeout menu %}
        {% menu %}
      {% endcache %}
      {% comment %} <div class="nav-item dropdown">
        <button class="nav-link btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">Лестница</button>
        <div class="dropdown-menu rounded-0 rounded-bottom m-0">
          {% for val in menu|dict:'staircases' %}
          <a href="{% url 'staircases:detail' val.slug %}" class="dropdown-item" itemprop="url">{{val.menu_name}}</a>
          {%endfor%}
        </div>
      </div>

      <div class="nav-item dropdown">
        <button class="nav-link btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">Крыльцо</button>
        <div class="dropdown-menu rounded-0 rounded-bottom m-0">
          {% for val in menu|dict:'porch' %}
          <a href="{% url 'porch:detail' val.slug %}" class="dropdown-item" itemprop="url">{{val.menu_name}}</a>
          {%endfor%}
        </div>
      </div>

      <a href="{% url 'terrace' %}" class="nav-item nav-link" itemprop="url">Терраса</a>

      <a href="{% url 'decorative-bridge' %}" class="nav-item nav-link" itemprop="url">Мостик</a>

      <div class="nav-item dropdown">
        <button class="nav-link btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">Ограждения</button>
        <div class="dropdown-menu rounded-0 rounded-bottom m-0">
          {% for val in menu|dict:'railings' %}
          <a href="{% url 'railings:detail' val.slug %}" class="dropdown-item" itemprop="url">{{val.menu_name}}</a>
          {%endfor%}
        </div>
      </div>

      <a href="{% url 'contacts' %}" class="nav-item nav-link" itemprop="url">Контакты</a> {% endcomment %}

    </div>
  </div>
</nav>